# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello_nbdev/',
                'doc_host': 'https://lgonzalezsa.github.io',
                'git_url': 'https://github.com/lgonzalezsa/hello_nbdev/',
                'lib_path': 'hello_nbdev'},
  'syms': {'hello_nbdev.core': {'hello_nbdev.core.say_hello': ('core.html#say_hello', 'hello_nbdev/core.py')}}}
