# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../notebooks/00_core.ipynb 3
def say_hello(
    to:str): # Name of the person to say hello! 
    "Say hello to somebody"
    return f'Hello {to}!'
